//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DescubraOAssassino.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DescubraOAssassino.Domain.Resources.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Arma incorreta!.
        /// </summary>
        internal static string ARMA_INCORRETA {
            get {
                return ResourceManager.GetString("ARMA_INCORRETA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe um {0} chamado {1}..
        /// </summary>
        internal static string JA_EXISTE_UM_X0_CHAMADO_X1 {
            get {
                return ResourceManager.GetString("JA_EXISTE_UM_X0_CHAMADO_X1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe uma {0} chamada {1}..
        /// </summary>
        internal static string JA_EXISTE_UMA_X0_CHAMADA_X1 {
            get {
                return ResourceManager.GetString("JA_EXISTE_UMA_X0_CHAMADA_X1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Você gostaria de nos ajudar a resolver um outro crime?.
        /// </summary>
        internal static string JOGAR_NOVAMENTE {
            get {
                return ResourceManager.GetString("JOGAR_NOVAMENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Local incorreto!.
        /// </summary>
        internal static string LOCAL_INCORRETO {
            get {
                return ResourceManager.GetString("LOCAL_INCORRETO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Operação realizada com sucesso..
        /// </summary>
        internal static string OPERACAO_REALIZADA_COM_SUCESSO {
            get {
                return ResourceManager.GetString("OPERACAO_REALIZADA_COM_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Assassino incorreto!.
        /// </summary>
        internal static string SUSPEITO_INCORRETO {
            get {
                return ResourceManager.GetString("SUSPEITO_INCORRETO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Parabéns! Você ajudou a resolver este crime!.
        /// </summary>
        internal static string TEORIA_CORRETA {
            get {
                return ResourceManager.GetString("TEORIA_CORRETA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} adicionada com sucesso!.
        /// </summary>
        internal static string X0_ADICIONADA_COM_SUCESSO {
            get {
                return ResourceManager.GetString("X0_ADICIONADA_COM_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} adicionado com sucesso!.
        /// </summary>
        internal static string X0_ADICIONADO_COM_SUCESSO {
            get {
                return ResourceManager.GetString("X0_ADICIONADO_COM_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} alterada com sucesso!.
        /// </summary>
        internal static string X0_ALTERADA_COM_SUCESSO {
            get {
                return ResourceManager.GetString("X0_ALTERADA_COM_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} alterado com sucesso!.
        /// </summary>
        internal static string X0_ALTERADO_COM_SUCESSO {
            get {
                return ResourceManager.GetString("X0_ALTERADO_COM_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} é obrigatória..
        /// </summary>
        internal static string X0_E_OBRIGATORIA {
            get {
                return ResourceManager.GetString("X0_E_OBRIGATORIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} é obrigatório..
        /// </summary>
        internal static string X0_E_OBRIGATORIO {
            get {
                return ResourceManager.GetString("X0_E_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} não encontrada..
        /// </summary>
        internal static string X0_NAO_ENCONTRADA {
            get {
                return ResourceManager.GetString("X0_NAO_ENCONTRADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} não encontrado..
        /// </summary>
        internal static string X0_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("X0_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} é obrigatório e deve conter entre {1} e {2} caracteres..
        /// </summary>
        internal static string X0_OBRIGATORIO_E_DEVE_CONTER_ENTRE_X1_E_X2_CARACTERES {
            get {
                return ResourceManager.GetString("X0_OBRIGATORIO_E_DEVE_CONTER_ENTRE_X1_E_X2_CARACTERES", resourceCulture);
            }
        }
    }
}
